version: '3.8'
services:
  mongodb:
    image: mongo:4.4.24
    container_name: mongodb
    ports:
      - '27017-27019:27017-27019'
  api:
    build: ./api
    container_name: questhub-api
    environment:
      - DATABASE_URI=mongodb://mongodb:27017
    ports:
      - '8000:8000'
    depends_on:
      - mongodb
    volumes:
      - data:/db

volumes:
    data:
