version: '3.8'
services:
  mongodb:
    image: mongodb/mongodb-community-server:6.0.6-ubuntu2204
    container_name: mongodb
    environment:
      - MONGODB_VERSION=4.4.24
    ports:
      - '27017-27019:27017-27019'
  api:
    build: ./api
    container_name: questhub-api
    environment:
      - DATABASE_URI=mongodb://mongodb:27017
    ports:
      - '8000:8000'
    depends_on:
      - mongodb

