version: '3.8'
services:
  mongodb:
    image: mongo:4.4.24
    container_name: mongodb
    ports:
      - '27017-27019:27017-27019'
    volumes:
      - mongo:/data/db
  api:
    build: ./api
    container_name: questhub-api
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - MONGODB_NAME=questhub
      - JWT_SECRET_KEY=E7fsZlgqWTjJfF5fuh0bVFI7ZjlQCeIX
      - JWT_REFRESH_SECRET_KEY=tUrCfQevEXg2PxqDXz2KVRB5CWd/P5Ws
      - CLIENT_URL=http://localhost:3000
    ports:
      - '8000:8000'
    depends_on:
      - mongodb
  client:
    build: ./client
    container_name: questhub-client
    ports:
      - '3000:3000'
    depends_on:
      - api
      

volumes:
  mongo:
